__author__ = "Sarah Lideus"
__copyright__ = "Copyright 2024, Sarah Lideus"
__email__ = "Sarah.Lideus.4744@student.uu.se"
__license__ = "GPL-3"


# Include pipeline specific rules
include: "rules/common.smk"
include: "rules/fastqc.smk"

# 'All' rule, must be specified before any other modules are
# included, since they also contain 'All' rule
rule all:
    input:
        compile_output_file_list,

