samples: "config/samples.tsv"
units: "config/units.tsv"

output: "config/output_list.yaml"
resources: "config/resources.yaml"

default_container: /castor/project/proj/poirot_pipeline/singularity_files/hydragenetics_common_0.3.0.sif

reference: 
  fasta: "/proj/naiss2024-22-121/pb_longread_pipeline/references/Hg38/ncbi_dataset/data/GCF_000001405.26/GCF_000001405.26_GRCh38_genomic.fna"

deepvariant:
  container: "/proj/naiss2024-22-121/nobackup/padraic/singularity_files/deepvariant_1.6.0.sif"
  
pbmm2_align_params:
  container: "/proj/naiss2024-22-121/nobackup/padraic/singularity_files/pbmm2_1.13.1.sif"
  preset: "HIFI"
  extra: "--sort"

#fastqc:
#  container: "docker://hydragenetics/fastqc:0.11.9"

#mosdepth:
#  container: "docker://hydragenetics/mosdepth:0.3.2"
#  by: "500"
#  extra: "--fast-mode --no-per-base "

#multiqc:
#  container: "docker://hydragenetics/multiqc:1.11"
#  reports:
#    DNA:
#      config: "config/multiqc_config_DNA.yaml"
#      included_unit_types: ["N"]
#      qc_files:
#        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq1_fastqc.zip"
#        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq2_fastqc.zip"
#        - "qc/mosdepth/{sample}_{type}.mosdepth.summary.txt"
#        - "qc/mosdepth/{sample}_{type}.mosdepth.region.dist.txt"
#        - "qc/mosdepth/{sample}_{type}.mosdepth.global.dist.txt"
#        - "qc/peddy/peddy.peddy.ped"
#        - "qc/peddy/peddy.background_pca.json"
#        - "qc/peddy/peddy.ped_check.csv"
#        - "qc/peddy/peddy.sex_check.csv"
#        - "qc/peddy/peddy.het_check.csv"
#        - "qc/peddy/peddy_sex_check_mqc.tsv"
#        - "qc/peddy/peddy_rel_check_mqc.tsv"
#        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
#        - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
#        - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.summary_metrics"
#        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
#        - "qc/picard_collect_insert_size_metrics/{sample}_{type}.insert_size_metrics.txt"
#        - "qc/picard_collect_wgs_metrics/{sample}_{type}.txt"
#        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
#        - "qc/samtools_idxstats/{sample}_{type}.samtools-idxstats.txt"
#        - "qc/verifybamid2/{sample}_{type}.selfSM"

#peddy:
#  container: "docker://hydragenetics/peddy:0.4.8"
#  config: "config/peddy_mqc.yaml"
#  extra: "--sites hg38 "

#samtools:
#  container: "docker://hydragenetics/common:0.3.0"



#deeptrio_call_variants:
#  container: "docker://google/deepvariant:deeptrio-1.4.0-gpu" #"docker://google/deepvariant:deeptrio-1.4.0-gpu"

#Egna grejer
#pbmm2:
#  container: "docker://hydragenetics/pbmm2:1.10" 

#hifiasm:
#  container: "docker://sarahstina/hifiasm:latest"
  
#common:
#  container: "docker://hydragenetics/common:1.10.2"

#whatshap:
#  container: "docker://hydragenetics/whatshap:1.7"

#pbsv:
#  container: "docker://hydragenetics/pbsv:2.9.0"

#sniffles2:
#  container: "docker://hydragenetics/sniffles2:2.0.7"

glnexus:
  container: "docker://hydragenetics/glnexus:1.4.1"

#xtea:
#  container: "docker://apaul7/xtea:0.1.9"

#somalier:
#  container: "docker://brentp/somalier:v0.2.19"




