samples: "/proj/sens2017554/nobackup/sarah/Masterarbete/PacBio_HIghFIve/config/samples.tsv"
units: "/proj/sens2017554/nobackup/sarah/Masterarbete//PacBio_HIghFIve/config/units.tsv"

output: "/proj/sens2017554/nobackup/sarah/Masterarbete/PacBio_HIghFIve/config/output_list.yaml"
resources: "/proj/sens2017554/nobackup/sarah/Masterarbete/PacBio_HIghFIve/config/resources.yaml"

default_container: /proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_common_1.10.2.sif

reference_files: 
  fasta_file: "/proj/sens2017554/nobackup/sarah/Masterarbete/static_resources/GRCh38/human_GRCh38_no_alt_analysis_set.fasta"
  bed_file: "/proj/sens2017554/nobackup/sarah/Masterarbete/static_resources/GRCh38/human_GRCh38_no_alt_analysis_set.trf.bed"
  sites_vcf: "/proj/sens2017554/nobackup/sarah/Masterarbete/reference_files/sites.hg38.vcf.gz"
  repeat_bed: "/proj/sens2017554/nobackup/sarah/Masterarbete/static_resources/GRCh38/trgt/human_GRCh38_no_alt_analysis_set.trgt.v0.3.4.bed"
  svanna-data: "/proj/sens2017554/nobackup/sarah/Masterarbete/reference_files/2304_hg38.svanna"
  pathogenic_repeats: "/proj/sens2017554/nobackup/sarah/Masterarbete/reference_files/pathogenic_repeats.hg38.bed"
  eee_vcf: "/proj/sens2017554/nobackup/sarah/Masterarbete/static_resources/GRCh38/sv_pop_vcfs/EEE_SV-Pop_1.ALL.sites.20181204.vcf.gz"
  gnomadsv_vcf: "/proj/sens2017554/nobackup/sarah/Masterarbete/static_resources/GRCh38/sv_pop_vcfs/nstd166.GRCh38.variant_call.vcf.gz"
  hprc_pbsv_vcf: "/proj/sens2017554/nobackup/sarah/Masterarbete/static_resources/GRCh38/sv_pop_vcfs/hprc.GRCh38.pbsv.vcf.gz"
  decode_vcf: "/proj/sens2017554/nobackup/sarah/Masterarbete/static_resources/GRCh38/sv_pop_vcfs/ont_sv_high_confidence_SVs.sorted.vcf.gz"
  gff: "/proj/sens2017554/nobackup/sarah/Masterarbete/static_resources/GRCh38/ensembl.GRCh38.101.reformatted.gff3.gz"

fastqc_params: 
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_fastqc_0.11.9.sif"

deepvariant_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/deepvariant_1.6.0.sif"
  model: "PACBIO"

pbmm2_align_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/pbmm2_1.13.1.sif"
  preset: "--preset HIFI"
  sort: "--sort"
  extra: "--log-level INFO"

mosdepth_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_mosdepth_0.3.2.sif"
  extra: "--fast-mode"
  by: "500"

samtools_stats_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_common_1.10.2.sif"

samtools_flagstat_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_common_1.10.2.sif"

samtools_idxstats_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_common_1.10.2.sif"

samtools_index_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_common_1.10.2.sif"

picard_collectalignmentsummarymetrics_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_picard_2.25.4.sif"

picard_collectgcbiasmetrics_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_picard_2.25.4.sif"

somalier_extract_params: 
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/brentp_somalier_v0.2.19.sif"

somalier_relate_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/brentp_somalier_v0.2.19.sif"
  ped: "/proj/sens2017554/nobackup/sarah/Masterarbete/PacBio_HIghFIve/config/samples.ped"

multiqc_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_multiqc_1.11.sif"

pbsv_discover_params: 
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_pbsv_2.9.0.sif"

pbsv_call_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_pbsv_2.9.0.sif"

whatshap_phase_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/whatshap_2.1.sif"
  indels: "--indels"
  ped: "/proj/sens2017554/nobackup/sarah/Masterarbete/PacBio_HIghFIve/config/samples.ped"

whatshap_stats_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/whatshap_2.1.sif"

whatshap_haplotag_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/whatshap_2.1.sif"

trgt_genotype_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/trgt_1.1.1.sif"
  prefix: "{trio}/repeat_calling/trgt/{sample}.{trio}.trgt.haplotagged.pathogenic"

trgt_plot_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/trgt_0.8.0.sif"

bcftools_stats_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/bcftools_1.14.sif"
  filter: "PASS"

bcftools_sort_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/bcftools_1.14.sif"
  type: "z"

bcftools_filter_snp_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/bcftools_1.14.sif"
  filter: '%QUAL>20 && FILTER="PASS" && MIN(DP)>3'

bcftools_filter_sv_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/bcftools_1.14.sif"
  filter: 'FILTER="PASS" && MIN(DP)>3'

bcftools_sort_trgt_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/bcftools_1.14.sif"

bcftools_index_trgt_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/bcftools_1.14.sif"

svanna_prioritize_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/svanna_1.0.4.sif"
  output_format: "html"
  outdir: "{trio}/sv_calling/svanna/"

tabix_index_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_common_1.10.2.sif"
  preset: "vcf"

bgzip_zip_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/hydragenetics_common_1.10.2.sif"

svpack_filter_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/svpack_36180.sif"
  min_sv_length: "50"

sniffles_call_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/sniffles_2.4.sif"

vep_annotate_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/ensemblorg_ensembl-vep_release_109.3.sif"
  mode: "--offline --cache --refseq"
  extra: "--assembly GRCh38 --check_existing --pick --sift b --polyphen b --ccds --symbol --af --af_1kg --af_gnomad --max_af"
  vep_cache: "/proj/sens2017554/nobackup/sarah/Masterarbete/reference_files/VEP/"

paraphase_params:
  container: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files/paraphase_3.1.1.sif"
  dir : "{trio}/cnv_calling/paraphase/"
