samples: "config/samples.tsv"
units: "config/units.tsv"

reference: 
	fasta:/proj/naiss2024-22-121/pb_longread_pipeline/references/Hg38/ncbi_dataset/data/GCF_000001405.26/GCF_000001405.26_GRCh30_genomic.fna

fastqc:
	container: "docker://hydragenetics/fastqc:0.11.9"

pbmm2:
	container: "docker://hydragenetics/pbmm2:1.10" 

mosdepth:
	container: "docker://hydragenetics/mosdepth:0.3.2"
	by: "500"
	extra: "--fast-mode --no-per-base "
