files:
  - name: multiqc_html
    output: "{trio}/results/qc/multiqc_{trio}.html"
    input: "{trio}/qc/multiqc/multiqc_{trio}.html"
  - name: whatshap_phase
    output: "{trio}/results/SNPs_indels/{sample}.{trio}.SNP.indel.phased.vcf"
    input: "{trio}/snp_calling/whatshap/{sample}.{trio}.SNP.indel.phased.vcf"
  - name: whatshap_haplotag
    output: "{trio}/results/Bam-files/{sample}.{trio}.aligned.sorted.haplotagged.bam"
    input: "{trio}/aligned/{sample}.{trio}.aligned.sorted.haplotagged.bam"
  - name: bcftools_sort
    output: "{trio}/results/SNPs_indels/{sample}.{trio}.SNP.indel.phased.sorted.vcf.gz"
    input: "{trio}/snp_calling/whatshap/{sample}.{trio}.SNP.indel.phased.sorted.vcf.gz"
  - name: bcftools_filter_snp
    output: "{trio}/results/SNPs_indels/{sample}.{trio}.SNP.indel.phased.sorted.filtered.vcf.gz"
    input: "{trio}/snp_calling/whatshap/{sample}.{trio}.SNP.indel.phased.sorted.filtered.vcf.gz"
  - name: bcftools_filter_sv
    output: "{trio}/results/SVs/{sample}.{trio}.haplotagged.sv.sorted.filtered.vcf.gz"
    input: "{trio}/sv_calling/pbsv/{sample}.{trio}.haplotagged.sv.sorted.filtered.vcf.gz"
  - name: pbsv_discover
    output: "results/{trio}/{sample}/pbsv/{sample}.{trio}.haplotagged.svsig.gz"
    input: "sv_calling/pbsv/{trio}/{sample}.{trio}.haplotagged.svsig.gz"
  - name: pbsv_call
    output: "{trio}/results/SVs/{sample}.{trio}.haplotagged.sv.vcf"
    input: "{trio}/sv_calling/pbsv/{sample}.{trio}.haplotagged.sv.vcf"
  - name: trgt_genotype_vcf
    output: "{trio}/results/repeat_expansion/{sample}.{trio}.trgt.haplotagged.vcf.gz"
    input: "{trio}/repeat_calling/trgt/{sample}.{trio}.trgt.haplotagged.vcf.gz"
  - name: trgt_genotype_bam
    output: "{trio}/results/repeat_expansion/{sample}.{trio}.trgt.haplotagged.spanning.bam"
    input: "{trio}/repeat_calling/trgt/{sample}.{trio}.trgt.haplotagged.spanning.bam"
  - name: tabix_index
    output: "{trio}/results/SNPs_indels/{sample}.{trio}.SNP.indel.phased.vcf.gz.tbi"
    input: "{trio}/snp_calling/whatshap/{sample}.{trio}.SNP.indel.phased.vcf.gz.tbi"
  - name: svanna_prioritize_html
    output: "{trio}/results/SVs/{sample}.{trio}.haplotagged.sv.sorted.svpack.SVANNA.html"
    input: "{trio}/sv_calling/svanna/{sample}.{trio}.haplotagged.sv.sorted.svpack.SVANNA.html"
  - name: svpack_filter
    output: "{trio}/results/SVs/{sample}.{trio}.haplotagged.sv.sorted.svpack.vcf.gz"
    input: "{trio}/sv_calling/svpack/{sample}.{trio}.haplotagged.sv.sorted.svpack.vcf.gz"
  - name: sniffles_call
    output: "{trio}/results/SVs/{sample}.{trio}.sv.haplotagged.sniffles.vcf.gz"
    input: "{trio}/sv_calling/sniffles/{sample}.{trio}.sv.haplotagged.sniffles.vcf.gz"
  - name: svpack_filter_sniffles
    output: "{trio}/results/SVs/{sample}.{trio}.sv.haplotagged.sniffles.svpack.vcf.gz"
    input: "{trio}/sv_calling/sniffles/{sample}.{trio}.sv.haplotagged.sniffles.svpack.vcf.gz"
  - name: vep_annotate
    output: "{trio}/results/SNPs_indels/{sample}.{trio}.SNP.indel.phased.sorted.filtered.annotated.vcf.gz"
    input: "{trio}/snp_calling/whatshap/{sample}.{trio}.SNP.indel.phased.sorted.filtered.annotated.vcf.gz"
  - name: paraphase
    output: "{trio}/results/cnv_calling/{sample}.{trio}.cnv.paraphase.json"
    input: "{trio}/cnv_calling/paraphase/{sample}.{trio}.cnv.paraphase.json"
