default_resources:
  threads: 1
  time: "12:00:00"
  mem_mb: 7168
  mem_per_cpu: 7168
  partition: "core"

fastqc_params:
  threads: 2
  time: "8:00:00"

pbmm2_align_params:
  threads: 16
  time: "15:00:00"
  mem_mb: 114688
  mem_per_cpu: 7168

mosdepth_params:
  threads: 4
  time: "05:00:00"

samtools_stats_params:
  threads: 4

samtools_flagstat_params:
  threads: 4

samtools_idxstats_params:
  threads: 4

deepvariant_params:
  threads: 16
  time: "24:00:00"
  mem_mb: 114688
  mem_per_cpu: 7168

whatshap_phase_params:
  threads: 4

whatshap_haplotag_params:
  threads: 4

pbsv_discover_params:
  threads: 16
  time: "48:00:00"
  mem_mb: 114688
  mem_per_cpu: 7168

pbsv_call_params:
  threads: 16
  time: "48:00:00"
  mem_mb: 114688
  mem_per_cpu: 7168

trgt_genotype_params:
  threads: 16
  time: "48:00:00"
  mem_mb: 114688
  mem_per_cpu: 7168

svanna_prioritize_params:
  threads: 8

whatshap_haplotag_params:
  threads: 4

svpack_filter_params:
  threads: 4
  time: "48:00:00"

sniffles_call_params:
  threads: 4
  time: "48:00:00"

vep_annotate_params:
  threads: 4

paraphase_params:
  threads: 4
