jobs: 1000
keep-going: True
restart-times: 0
rerun-incomplete: True
max-jobs-per-second: 100
max-status-checks-per-second: 100
use-singularity: True
snakefile: "/proj/sens2017554/nobackup/sarah/Masterarbete/PacBio_HIghFIve/workflow/Snakefile"
configfile: "/proj/sens2017554/nobackup/sarah/Masterarbete/PacBio_HIghFIve/config/config_bianca.yaml"
# set -A in drmaa to the bianca project id
drmaa: "-A sens2017554 -p {resources.partition}  -t {resources.time} -n {resources.threads} --mem={resources.mem_mb} --mem-per-cpu={resources.mem_per_cpu} -J {rule}  -e slurm$
#default-resources:
#  - gres=""
#  - constraint=""
drmaa-log-dir: "slurm"
singularity-args: "--cleanenv --bind /castor/project/proj,/proj --disable-cache --nv"
singularity-prefix: "/proj/sens2017554/nobackup/sarah/Masterarbete/singularity_files"
